<?php

/**
 * @file lit_blocks.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_block_info().
 */
function lit_blocks_block_info() {
  $blocks['landing_page_options'] = array(
    'info' => t('Landing page options'),
    'cache' => DRUPAL_NO_CACHE
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function lit_blocks_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'landing_page_options':
    	$module_path = drupal_get_path('module', 'lit_blocks');
    	$full_path = $module_path .'/lit_blocks.css';
    	drupal_add_css($full_path);
      //$block['subject'] = t('Landing Page Options');
      $block['subject'] = '';
      $output = array(
      	'blokcito01' => array(
          '#type' => 'markup',
          '#prefix' => '<div class="blokcito">',
          '#suffix' => '</div>',
      		'#markup' => '<p>Hola, chicos (1) !</p>',
        ),
      	'blokcito02' => array(
          '#items' => array('Do this', 'Do that', 'Do the other!'),
          '#theme' => 'item_list',
          '#prefix' => '<div class="blokcito">',
          '#suffix' => '</div>',
        ),
      	'blokcito03' => array(
          '#type' => 'markup',
          '#prefix' => '<div class="blokcito">',
          '#suffix' => '</div>',
      		'#markup' => '<p>Hola, chicos (3) !</p>',
        ),
      );
      $block['content'] = $output;
      break;
  }
  return $block;
}
/**
 * Implements hook_theme().
 */
/*
function lit_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'forum_display' => array(
      'variables' => array('forums' => NULL, 'topics' => NULL, 'parents' => NULL, 'tid' => NULL, 'sortby' => NULL, 'forum_per_page' => NULL),
    ),
    'forum_list' => array(
      'variables' => array('forums' => NULL, 'parents' => NULL, 'tid' => NULL),
    ),
    'forum_topic_list' => array(
      'variables' => array('tid' => NULL, 'topics' => NULL, 'sortby' => NULL, 'forum_per_page' => NULL),
    ),
    'forum_icon' => array(
      'variables' => array('new_posts' => NULL, 'num_posts' => 0, 'comment_mode' => 0, 'sticky' => 0),
    ),
    'status_report' => array(
      'render element' => 'requirements',
      'file' => 'system.admin.inc',
    ),
    'system_date_time_settings' => array(
      'render element' => 'form',
      'file' => 'system.admin.inc',
    ),
  );
}
*/
